cask_args appdir: '/Applications'
tap 'caskroom/cask'
cask 'google-chrome'
cask 'atom'
cask 'sourcetree'
cask 'polymail'
cask 'dropbox'
cask 'google-drive'
cask 'sketch'
cask 'font-fontawesome'
cask 'backblaze'
cask 'dropbox'
